// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4HkdE_5qss19tbKC8XohENyl9aiLntYo',
    appId: '1:905048566518:web:3079ca61c373fd44b95ad7',
    messagingSenderId: '905048566518',
    projectId: 'pokedex-flutter-80c47',
    authDomain: 'pokedex-flutter-80c47.firebaseapp.com',
    storageBucket: 'pokedex-flutter-80c47.appspot.com',
    measurementId: 'G-8L2FE4V59F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFnsezzKBQkGX-aaX1kuNJ_K500gaUbIQ',
    appId: '1:905048566518:android:e6a8be3b83af59f4b95ad7',
    messagingSenderId: '905048566518',
    projectId: 'pokedex-flutter-80c47',
    storageBucket: 'pokedex-flutter-80c47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDogWThrMQ63uglarUpCqcCNl5-9iK2B3M',
    appId: '1:905048566518:ios:75e7152b299e8f66b95ad7',
    messagingSenderId: '905048566518',
    projectId: 'pokedex-flutter-80c47',
    storageBucket: 'pokedex-flutter-80c47.appspot.com',
    iosClientId: '905048566518-mcb4kat3kk6g5p1j1b57jqone5rcu260.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDogWThrMQ63uglarUpCqcCNl5-9iK2B3M',
    appId: '1:905048566518:ios:e61de2f0bb4d62a6b95ad7',
    messagingSenderId: '905048566518',
    projectId: 'pokedex-flutter-80c47',
    storageBucket: 'pokedex-flutter-80c47.appspot.com',
    iosClientId: '905048566518-5k67a50ve7v7kd2csaiouuf1igo9g1qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedex.RunnerTests',
  );
}
